### ISSUE TITLE
sugar-toolkit-gtk3 deprecated functions

### ISSUE THREAD

**Issue by aperezbios** [sugarlabs/sugar-toolkit-gtk3#437] opened 2019-12-30 22:41 UTC
When compiling sugar-toolkit-gtk3, warnings for the following functions, which are now deprecated, are issued:

gdk_display_get_device_manager is deprecated
gdk_screen_make_display_name is deprecated
gdk_screen_get_number is deprecated
gdk_threads_enter is deprecated
gdk_threads_leave is deprecated
gdk_error_trap_pop is deprecated
gdk_error_trap_pop_ignored is deprecated
gdk_error_trap_push is deprecated
g_type_class_add_private is deprecated

**Comment by quozl** [comment] 2019-12-31 08:03
Thanks for testing.  Duplicate of https://github.com/sugarlabs/sugar-toolkit-gtk3/issues/404.

**Closed** 2022-01-26 16:39 UTC
